### Feb 26, Numpy Assignment - Part 4

Consider the below code to answer further questions:

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

#### Ans: 
Yes, there is a difference in the data type of variables list_ and array_list as list_ variable is of type list and array_list is of type array but they both are string in  python. We can see the data type of these two variables using the code below:

In [8]:
import numpy as np

list_ = [ '1', '2', '3', '4', '5' ]

array_list = np.array(object = list_)

print("The datatype of the list_ is ", type(list_))
print("The datatype of the array_list", type(array_list))

The datatype of the list_ is  <class 'list'>
The datatype of the array_list <class 'numpy.ndarray'>


#### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [10]:
# program to print the data type of variable list_
data_type1 = []
for element in list_:
    data_type1.append(type(element))
print(data_type1)


#  program to print the data type of variable array_list
data_type2 = []
for every_element in array_list:
    data_type2.append(type(every_element))
print(data_type2)

[<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]
[<class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>]


#### Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int) Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

#### Ans:
Yes, there will be the differences in the data type of the elements present in both the the variables as the list_ variable will be having string type for the elements but the array_list will be having int type of the data.

In [15]:
# change the data type of the element of the array_list
array_list = np.array(object= list_, dtype = int)

# check the dtype of the element in the variable array_list
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [17]:
# check the data type of the element for list_ variable
for j in list_:
    print(type(j))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


Here,now we can see that the data type of the element in array_list is int type but that of the list_ is still string type. So, 

Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

#### Q4. Write a code to find the following characteristics of variable, num_array:
- (i) shape
- (ii) size

In [21]:
## Ans:
import numpy as np 
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ] 
num_array = np.array(object = num_list)

# To find the shape and size of the array, shape and size properties can be used
print("The shape and the size of the num_array are as follow respectively: \n\n\n", 
      "Shape:",num_array.shape, " \n\n Size: ", num_array.size)

The shape and the size of the num_array are as follow respectively: 


 Shape: (2, 3)  

 Size:  6


#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy arra  creation function. [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [32]:
# import the necessary library
import numpy as np
zero_matrix = np.zeros((3,3))

In [33]:
# indentity matrix of rank 3 X 3 with all the elements zeros
zero_matrix

# print the shape and size of the matrix
print("The shape of the matrix :",zero_matrix.shape, "\n\nThe size of the matrix :",zero_matrix.size)

The shape of the matrix : (3, 3) 

The size of the matrix : 9


#### Q6. Create an identity matrix of shape (5,5) using numpy functions? [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [35]:
import numpy as np
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
